### ISSUE TITLE
Latest version Livet throws error on WPF.

### ISSUE THREAD

**Issue by nrajasekar7** [runceel/Livet#45]
@runceel @karno @Gab-km @YoshihiroIto @ledsun 
Hi,
My WPF (.Net framework) 4.5.2 application was using older version of LivetCask(2.2.0), that time it was working fine.
Now i updated the LivetCask into 3.2.1. When updating the latest package using Nuget, some other LivetCask components also installed.

The blow code shows error : 
the value of type can not be added to a collection or dictionary of type triggeractioncollection for event trigger.

`<i:Interaction.Triggers>
        <i:EventTrigger EventName="ContentRendered">           
          <l:LivetCallMethodAction MethodTarget="{Binding}" MethodName="Initialize"/>
        </i:EventTrigger>
        <i:EventTrigger EventName="Closed">
            <l:DataContextDisposeAction/>
        </i:EventTrigger>
        <l:InteractionMessageTrigger Messenger="{Binding Path=Messenger}" MessageKey="ok">
            <l:WindowInteractionMessageAction/>
        </l:InteractionMessageTrigger>
        <l:InteractionMessageTrigger Messenger="{Binding Path=Messenger}" MessageKey="cancel">
            <l:WindowInteractionMessageAction/>
        </l:InteractionMessageTrigger>
    </i:Interaction.Triggers>`

Please help me on this.

**Comment by runceel** [comment]
Hi @nrajasekar7 ,

Thank you for the report.
I think that the error is occurred to one of the breaking changes.

I decided replacing Blend SDK to `Microsoft.Xaml.Behaviors.Wpf` when I released `v3.0.0`, because Blend SDK was became to not include to Visual Studio 2019.

Please migrate to the new behavior library on your project, the details is as the following link:
https://devblogs.microsoft.com/dotnet/open-sourcing-xaml-behaviors-for-wpf/

**Comment by nrajasekar7** [comment]
Hi @runceel ,

Thank you very much for your prompt response. 
The issue got resolved by referring the behaviors.wpf.

Thanks,
Rajasekar

**Comment by runceel** [comment]
Hi @nrajasekar7 ,

I'm happy to hear you fixed the issue.
Thank you!
